version: '3'

services:
  app:
    container_name: app-server
    restart: always
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DBHOST: pgsql
      DBPORT: 5432
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
    depends_on:
      - pgsql
    links:
      - pgsql

  pgsql:
    container_name: pgsql-server
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    volumes:
      - pg-data:/var/lib/postgresql/data

  # Optional
  pgadmin:
    container_name: pgadmin-server
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: acmud@acm.org
      PGADMIN_DEFAULT_PASSWORD: ${DBPASS}
    ports:
      - 8080:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - pgsql
    links:
      - pgsql

volumes:
  pg-data:
  pgadmin-data:
